#Sales Records Analysis
###Author: Mina Saeday
### Exercise 2.E Using functions for analyzing data
This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argumen

In [1]:
sales_data = [
    ('Laptop', 'East', 1200.00),
    ('Phone', 'West', 850.00),
    ('Tablet', 'East', 400.00),
    ('Monitor', 'South', 650.00),
    ('Keyboard', 'West', 75.00),
    ('Laptop', 'South', 1150.00),
    ('Phone', 'East', 900.00),
    ('Tablet', 'West', 425.00),
    ('Monitor', 'East', 680.00),
    ('Keyboard', 'South', 80.00),
    ('Laptop', 'West', 1300.00),
    ('Phone', 'West', 820.00),
]


## Lab 1. Total sales by region


In [9]:
def region_total(data, region):
    return sum(amt for p, r, amt in data if r == region) 

In [10]:
print(region_total(sales_data,'East'))
print(region_total(sales_data,'West'))
print(region_total(sales_data,'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [ ]:
def region_count(data, region):
    return sum(1 for p, r, amt in data if r == region)

In [19]:
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))


4
5
3


In [20]:
print(len(sales_data))  # This is just to see the total as an alternative


12


## Lab 3. Average sale amount by region

In [23]:
def region_average(data,region):
    count = region_count(data,region)
    if count == 0:
        return 0
    return region_total(data,region) / count

In [26]:
print(region_average(sales_data,'East'))
print(region_average(sales_data,'West'))
print(region_average(sales_data,'South'))
print(region_average(sales_data,'North'))

795.0
694.0
626.6666666666666
0


## Lab 4.Filter by sale amount

In [27]:
def sales_above(data, threshold):
    return [ (p, r, amt) for p, r, amt in data if amt > threshold]

In [30]:
results = sales_above(sales_data,500)

for record in results:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


In [34]:
def sales_below(data, threshold):
    return [ (p, r, amt) for p, r, amt in data if amt < threshold]

In [35]:
results = sales_below(sales_data, 500)

for record in results:
    print(record)

('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


## Lab 5 Top and bottom sale

In [43]:
def top_sale(data):
    return max(data, key=lambda s: s[2])

def bottom_sale(data):
    return min(data, key=lambda s: s[2])

In [44]:
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The top sale was a Laptop  in the west region for $1300.00.
The bottom sale was a keyboard in the West region for $75.00.


## Lab 6. Apply a discount

In [49]:
def apply_discount(data, discount_pct):
    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))

In [50]:
discounted_data = apply_discount(sales_data, 0.15)

print("Before:")
for record in sales_data[:3]:
    print(record)

print("After:")
for record in discounted_data[:3]:
    print(record)

Before:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)
After:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab7. Unique regions

In [53]:
def unique_regions(data):
    return sorted(set(r for _, r, _ in data))

In [54]:
print(unique_regions(sales_data))

['East', 'South', 'West']


This function could be useful in a longer analysis program because it helps identify all of the different categories in a dataset without duplicates. In this example, it shows all regions that appear in the sales data. A pattern like this could also be used to find unique product names, departments, cities, or customer groups before doing deeper analysis such as grouping, counting, or summarizing data by category.


## Lab 8. Region summary

In [60]:
def region_summary(data, region):
    total = region_total(data,region)
    count = region_count(data, region)
    average = region_average(data, region)

    region_data = [record for record in data if record [1] == region]
    top = top_sale(region_data)

    print(f"=== {region} Region ===")
    print(f"Records:     {count}")
    print(f"Total Sales:  ${total:,.2f}")
    print(f"Average Sale: ${average:,.2f}")
    print(f"Top Sale:      {top[0]} - ${top[2]:,.2f}")

In [61]:
region_summary(sales_data, 'East')
region_summary(sales_data, 'West')
region_summary(sales_data,  'South')

=== East Region ===
Records:     4
Total Sales:  $3,180.00
Average Sale: $795.00
Top Sale:      Laptop - $1,200.00
=== West Region ===
Records:     5
Total Sales:  $3,470.00
Average Sale: $694.00
Top Sale:      Laptop - $1,300.00
=== South Region ===
Records:     3
Total Sales:  $1,880.00
Average Sale: $626.67
Top Sale:      Laptop - $1,150.00


## Lab 9. Full summary

In [63]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)
    print()

=== East Region ===
Records:     4
Total Sales:  $3,180.00
Average Sale: $795.00
Top Sale:      Laptop - $1,200.00

=== South Region ===
Records:     3
Total Sales:  $1,880.00
Average Sale: $626.67
Top Sale:      Laptop - $1,150.00

=== West Region ===
Records:     5
Total Sales:  $3,470.00
Average Sale: $694.00
Top Sale:      Laptop - $1,300.00

